- name: install maven
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: "present"
  loop:
    - maven
    - mysql
- name: install PyMySQL and cryptography using pip
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3
  loop:
    - PyMySQL
    - crypthography

- name: install maven dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: "{{ app_dir }}"
- name: rename jar file
  ansible.builtin.command: mv target/{{ server_name }}-1.0.jar {{ server_name }}.jar
  args:
    chdir: "{{ app_dir }}"