- name: install maven
  ansible.builtin.dnf:
    name: maven
    state: "present"
- name: install maven dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: "{{ app_dir }}"
- name: rename jar file
  ansible.builtin.command: mv target/{{ server_name }}-1.0.jar {{ server_name }}.jar
  args:
    chdir: "{{ app_dir }}"