- name: install packages like python3 gcc python3-devel
  ansible.buiiltin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - gcc
    - python3-devel
  
- name: install python dependencies
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3
  args:
    chdir: "{{ app_dir }}"
