- name: "Ensure {{ app_user }} system user exists"
  user:
    name: "{{ app_user }}"
    state: present
    shell: /sbin/nologin
    system: yes
  register: roboshop_user_result

- name: "Ensure {{ app_dir }} directory exists for {{ app_user }}"
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
  when: roboshop_user_result.changed

- name: download and extract {{ server_name }} code in {{ app_dir }}
  unarchive:
    src: "https://roboshop-artifacts.s3.amazonaws.com/{{ server_name }}-v3.zip"
    dest: "{{ app_dir }}"
    remote_src: yes
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'



    
  

