- name: copy systemd service file
  ansible.builtin.template:
    src: files/catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service
    mode: "0644"  
- name: daemon-reload systemd service
  ansible.builtin.systemd_service:
    daemon_reload: yes
- name: ensuring catalogue service is enabled and restarted
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes  

    